In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({'id': [1, 2, 3, 4, 5, 6], 'name': ['dog', 'cat', 'mad cat', 'good dog', 'bad dog', 'chicken']})
df

id      name
0   1       dog
1   2       cat
2   3   mad cat
3   4  good dog
4   5   bad dog
5   6   chicken

In [3]:
# Creating 2 pandas Series
ps1 = pd.Series([2.5, 4, 6, 8, 10, 1.75, 40])
ps2 = pd.Series([1.5, 3, 5, 7, 10, 1.75, 20])
  
print("Series1:")
print(ps1)
print("\nSeries2:")
print(ps2)
  
# Compare the series using '==' and '!=' 
# Relational operators
print("\nCompare the elements of the two given Series:")
print("\nEqual:")
print(ps1 == ps2)
print("\nNot Equal:")
print(ps1 != ps2)

Series1:
0     2.50
1     4.00
2     6.00
3     8.00
4    10.00
5     1.75
6    40.00
dtype: float64

Series2:
0     1.50
1     3.00
2     5.00
3     7.00
4    10.00
5     1.75
6    20.00
dtype: float64

Compare the elements of the two given Series:

Equal:
0    False
1    False
2    False
3    False
4     True
5     True
6    False
dtype: bool

Not Equal:
0     True
1     True
2     True
3     True
4    False
5    False
6     True
dtype: bool


In [4]:
from scipy.sparse import csr_matrix
import numpy as np

In [5]:
a =  csr_matrix((3, 4), dtype=np.int8).toarray()

In [6]:
arr = np.array([0, 0, 0, 0, 0, 1, 1, 0, 2])

mat = csr_matrix(arr)

max =  float(mat.getcol(mat.argmax()).data )


In [7]:
print(mat)

  (0, 5)	1
  (0, 6)	1
  (0, 8)	2


In [8]:
a  = mat / max
print(a)

  (0, 5)	0.5
  (0, 6)	0.5
  (0, 8)	1.0


In [9]:
df = pd.DataFrame({'id': [1, 2, 3, 4, 5, 6], 'name': ['dog', 'cat', 'mad cat', 'good dog', 'bad dog', 'chicken']})
df

id      name
0   1       dog
1   2       cat
2   3   mad cat
3   4  good dog
4   5   bad dog
5   6   chicken

In [10]:
df_compare = pd.DataFrame({'id': [1, 2, 3], 'name': ['dog', 'cat', 'mad cat']})
df_compare['RC'] = 9
df_compare

id     name  RC
0   1      dog   9
1   2      cat   9
2   3  mad cat   9

In [11]:
from fuzzywuzzy import fuzz
name = 'dog'
df.apply(lambda row: (fuzz.partial_ratio(row['name'], name) >= 85), axis=1)

/home/sokhorn/.local/lib/python3.8/site-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')


0     True
1    False
2    False
3     True
4     True
5    False
dtype: bool

In [12]:
def func(name):
    matches = df.apply(lambda row: (partial_ratio(row['name'], name) >= 85), axis=1)
    return [i for i, x in enumerate(matches) if x]

In [13]:
df1 = pd.DataFrame({'Name':['Sara','Patrik'],'Special ability':['Walk on water','FireBalls'],'Age':[4,11]})

df1

Name Special ability  Age
0    Sara   Walk on water    4
1  Patrik       FireBalls   11

In [14]:
df2 = pd.DataFrame({'Name':['Sara', 'Gustaf', 'Patrik'],'Age':[4,12,11]})
df2

Name  Age
0    Sara    4
1  Gustaf   12
2  Patrik   11

In [15]:
df = df2.merge(df1,left_on=['Name','Age'],right_on=['Name','Age'],how='left')
df

Name  Age Special ability
0    Sara    4   Walk on water
1  Gustaf   12             NaN
2  Patrik   11       FireBalls

In [16]:
#  sum each row pandas 
df = pd.DataFrame({'a': [1,2,3], 'b': [2,3,4], 'c':['dd','ee','ff'], 'd':[5,9,1]})
df

a  b   c  d
0  1  2  dd  5
1  2  3  ee  9
2  3  4  ff  1

In [17]:
df['e'] = df.sum(axis=1)
df

/tmp/ipykernel_36374/1508361881.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df['e'] = df.sum(axis=1)


a  b   c  d   e
0  1  2  dd  5   8
1  2  3  ee  9  14
2  3  4  ff  1   8

In [18]:
df = pd.DataFrame([(234.0, 289.0),
                   (135.0, 224.0),
                   (23.0, 80.5),
                   (53.0, 25.30)],
           columns=('AvgBill1', 'AvgBill2')
                 )
df

AvgBill1  AvgBill2
0     234.0     289.0
1     135.0     224.0
2      23.0      80.5
3      53.0      25.3

In [19]:
df.append(df.sum(numeric_only=True), ignore_index=True)

AvgBill1  AvgBill2
0     234.0     289.0
1     135.0     224.0
2      23.0      80.5
3      53.0      25.3
4     445.0     618.8

In [20]:
pd.DataFrame(df.sum(axis=0))

0
AvgBill1  445.0
AvgBill2  618.8

In [21]:
def f(df, indices):
    result = df.iloc[indices[0]]
    for i in range(1,len(indices)):
        result = result & df.iloc[indices[i]]
    return result

df = pd.DataFrame([[7, 7, 7, 8], [1, 2, 4, 8], [13, 2, 13, 13], [1, 7, 14, 13]])
indices = [0,1,3]
result = f(df, indices)
print(result)

0    1
1    2
2    4
3    8
dtype: int64


In [22]:
df

0  1   2   3
0   7  7   7   8
1   1  2   4   8
2  13  2  13  13
3   1  7  14  13

In [23]:
indices

[0, 1, 3]

In [24]:
"""
Singular Value Decomposition
"""
# define a matrix

'\nSingular Value Decomposition\n'

In [25]:
X = np.array([[3, 3, 2], [2,3,-2]])
X

array([[ 3,  3,  2],
       [ 2,  3, -2]])

In [26]:
u, s, vh =  np.linalg.svd(X)

In [27]:
u

array([[-0.7815437, -0.6238505],
       [-0.6238505,  0.7815437]])

In [28]:
s

array([5.54801894, 2.86696457])

In [29]:
vh

array([[-0.64749817, -0.7599438 , -0.05684667],
       [-0.10759258,  0.16501062, -0.9804057 ],
       [-0.75443354,  0.62869461,  0.18860838]])

In [50]:
fk = [ "Item1",
    "Item2",
    "Item3",
    "Item4",]


In [52]:
len(fk)

4

ValueError: list.remove(x): x not in list